### ISSUE TITLE
Token state missmatch due to url encoding and state disappears from adal context.

### ISSUE THREAD

**Issue by kov-hans** [grumar/adal-angular5#15]
Hi!
After a successfull id_token retreival I'm making a call to aquireToken like this:
this.service.acquireToken("https://<tenant>/<guid>").subscribe((token) => {console.log("Access token:" + token)}, (error) => {console.log("Error" + error);});
I then see an authorize request beeing sent over the network  where the state is set to <guid>|<url-encoded resource>.
But the state that is saved in the _renewStates property in the adal context has NOT an url-encoded resource.
When I debug "handleWindowCallback" I see that an access_token is received but there are two problems.
The _renewStates in the adal context in the handleWindowCallback is empty, why is that? Even if the _renewStates wasn't empty adal would still not find a match due to that the received state is url-encoded but the state saved when sending the request is NOT url-encoded. Am I doing something wrong? Please help!

**Comment by grumar** [comment]
Duplicates #18
