### ISSUE TITLE
Unable to read tokn since angular 5.2.8

### ISSUE THREAD

**Issue by AnthonyGiretti** [grumar/adal-angular5#24]
Hi!

Angular 5.2.8 has been released
https://github.com/angular/angular/blob/master/CHANGELOG.md

The library doesn’t work anymore, it’s unable to read the token from hash.
Angular team has updated special chars management in the URI, maybe it causes the issue? 

What can we do instead of keeping angular 5.2.7 or lower?

Thank you so much!

**Comment by lucax88x** [comment]
Agreed, hashes are now getting encoded..

**Comment by AnthonyGiretti** [comment]
Hi,

Just need to make this to make it work:

hash = decodeURIComponent(window.location.hash);
window.location.hash = hash;

I did it before adal reads the hash.

Can you integrate this in an update of your package?

**Comment by leonixyz** [comment]
benbaran/adal-angular4 currently works fine also with angular5, the owner is active and there is a larger user base. Consider switching to that library

**Comment by AnthonyGiretti** [comment]
Did you tried it with angular 5.2.8?
I’m pretty sure there is the same issue with the package you are proposing

**Comment by leonixyz** [comment]
Yes, I confirm benbaran/adal-angular4 works with angular 5.2.8.

**Comment by AnthonyGiretti** [comment]
According to me it’s not possible, explanation in my previous comment

**Comment by grumar** [comment]
@leonixyz adal-angular4 works when you use old `Http` which is marked as deprecated, for angular 4.3 and above you should use `HttpClient` instead.
[difference betwwen Http and HttpClient](https://stackoverflow.com/questions/45129790/difference-between-http-and-httpclient-in-angular-4)

**Comment by leonixyz** [comment]
@grumar latest versions work with `HttpClient`

**Comment by AnthonyGiretti** [comment]
Issue is fixed. Angular has been updated, and fixed the issue.
