### ISSUE TITLE
Get Token http error

### ISSUE THREAD

**Issue by chigivigi** [grumar/adal-angular5#4]
I am working in a single page application in which i trying to get token from my backend application. I have followed the example on this site https://github.com/benbaran/adal-angular4-example to initialize the authentication. Immediately after the application is authorized I am calling my service to acquire token for my backend application but I receive the error for my service:

[AuthService -> Http]:   NullInjectorError: No provider for Http! 

In the service I call a method that calls Adal5Service acquireToken method. Is there a way to call the acquire token method without triggering the error ?

I am working in angular version 5.20.

**Comment by grumar** [comment]
Probably this is because You're providing `AdalAngular5` in this way:
```
providers: [
        Adal5Service,
        { provide: Adal5HTTPService, useFactory: Adal5HTTPService.factory, deps: [Http, Adal5Service] } 
  ]
```
but You should:
```
providers: [
        Adal5Service,
        { provide: Adal5HTTPService, useFactory: Adal5HTTPService.factory, deps: [HttpClient, Adal5Service] } 
  ]
```
__different deps `HttpClient` instead of `Http`__

I added example in [Readme](https://github.com/grumar/adal-angular5/blob/master/README.md)

**Comment by chigivigi** [comment]
I changed http to httpclient in my application and it stills does not work. Can it be something else ?
