### ISSUE TITLE
Access token Expiry - 401 Unauthorized on AJAX

### ISSUE THREAD

**Issue by LooseThreads** [grumar/adal-angular5#42]
Hi,

I'm trying to use adal-angular5 to handle authentication for my application with azure AD.

My routeGuard works fine with this logic:
```
    if (this._adal.userInfo.authenticated) {
      return true;
    }
    this_adal.login();
    return false;
```
allowing navigation from page to page even after access token expiry, but any AJAX requests are failing with 401 unauthorized, how do I force the re-authentication logic to renew the access token in the event of an AJAX failure/hide access token expiry completely from the user such that the application can be left unattended for 1 hour and still work?

Any working examples would be greatly appreciated.

**Comment by nmagesh84** [comment]
I too have the same problem , API service throws 401 since the token is expired. We need to refresh the token silently without the user's attention. 

Please share any working examples. Thanks

**Comment by LooseThreads** [comment]
So the problem I was having was caused by manually setting the Authorization header, the token in storage isn't updated when a new one is acquired by this library, so setting the header manually will inject an expired token before the valid one is added, causing a 401.

A related issue was that My client and API are on different URLs, and this isn't supported by the default behavior, so manually specifying the endpoint in the config is required to allow automatic token acquisition by this library.

const config = {                           
  tenant: '***********************************',
  clientId: 'CLIENTIDGOESHERE',
  cacheLocation: 'localStorage',
  endpoints: {
'http://localhost:44302' : 'CLIENTIDGOESHERE'
}
}
