### ISSUE TITLE
http get

### ISSUE THREAD

**Issue by mihaipopescu0409** [grumar/adal-angular5#6]
I have changed the providers in app.module to HttpClient, and imported HttpClientModule.

But when i want to make a get request, i am asked to provide 2 params: url and options. In the adal angular4, options parameter is optional. 
I can't provide an empty dict (can't compile with empty options), and if i change in your source code the options parameter to be optional for get method, i get this error 

```
Cannot read property 'toLowerCase' of undefined
    at HttpXsrfInterceptor.intercept (http.js:2482)
```

How should i do it? 

My angular version is 5.0, and angular-cli: 1.6.3.

It appears that i'm not the only one who struggles with this library, perhaps you could provide us an example.

Thank you

**Comment by grumar** [comment]
Example added in Readme b1bf2fa0e922f7aaa4f3f833562c35d7565f903d.

**Comment by mihaipopescu0409** [comment]
Still can't get this to work

I have created a new service called HttpService (from your new updated readme file), that looks like this

```
import {Injectable} from '@angular/core';
import {Adal5HTTPService, Adal5Service} from 'adal-angular5';
import {Observable} from 'rxjs/Observable';
import {HttpHeaders} from '@angular/common/http';

@Injectable()
export class HttpService {
  constructor(
    private adal5HttpService: Adal5HTTPService,
    private adal5Service: Adal5Service
  ) {}

  public get(url: string): Observable<any> {
    const options = this.prepareOptions();
    return this.adal5HttpService.get(url, options);
  }

  private prepareOptions(): any {
    let headers = new HttpHeaders();
    headers = headers
      .set('Content-Type', 'application/json')
      .set('Authorization', `Bearer ${this.adal5Service.userInfo.token}`);
    return { headers };
  }
}
```
I have injected it in my app.module.ts under providers, so my app.module.ts looks like this:

```
  providers: [
    { provide: LocationStrategy, useClass: HashLocationStrategy },
    Adal5Service,
    { provide: Adal5HTTPService, useFactory: Adal5HTTPService.factory, deps: [HttpClient, Adal5Service] },
    HttpService
    ],
```

Now in my component, in the constructor i have injected the httpService, and when i want to make a get request:

`this.httpService.get(url).subscribe(result => console.log(result));`

In my browser console, i obtain:

```
 req.url.toLowerCase is not a function
    at HttpXsrfInterceptor.intercept (http.js:2482)
```

What am i doing wrong?
Thank you
